name: view_model
description: A state management system for Flutter with support for lifecycle-aware View Models, events, and asynchronous Actions.
version: 0.0.1
author: Lukasz Ciastko

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
